# Generated by Django 4.2.5 on 2023-09-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
