# Generated by Django 4.2.3 on 2023-09-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_albums_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='price',
            new_name='limit',
        ),
        migrations.RemoveField(
            model_name='albums',
            name='description',
        ),
    ]
