# Generated by Django 4.2.3 on 2023-09-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_rename_price_albums_limit_remove_albums_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='albums',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
