# Generated by Django 4.2.3 on 2023-09-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_category_options_and_more'),
        ('albums', '0004_albums_counter_albums_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='genre',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
