# Generated by Django 3.2.21 on 2023-10-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_albums_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
