# Generated by Django 4.2.5 on 2023-10-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_category_options_and_more'),
        ('albums', '0006_albums_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='genre',
            field=models.ManyToManyField(blank=True, to='category.category'),
        ),
    ]
