# Generated by Django 4.2.5 on 2023-10-04 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0027_merge_20231004_1125'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0007_alter_albums_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='movies',
        ),
        migrations.CreateModel(
            name='AlbumMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.albums')),
                ('movies', models.ManyToManyField(to='indexapp.moviedetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
