# Generated by Django 4.2.5 on 2023-10-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_remove_albums_counter_albummovie_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
