# Generated by Django 4.2.5 on 2023-10-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_albummovie_separator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albummovie',
            name='separator',
        ),
        migrations.AddField(
            model_name='albums',
            name='separator',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
