# Generated by Django 4.2.5 on 2023-10-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_remove_albummovie_separator_albums_separator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='separator',
        ),
        migrations.AddField(
            model_name='albummovie',
            name='separator',
            field=models.IntegerField(null=True),
        ),
    ]
