# Generated by Django 4.2.5 on 2023-10-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0014_seprator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seprator',
            old_name='seprator',
            new_name='separator',
        ),
    ]
