# Generated by Django 4.2.5 on 2023-10-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0015_rename_seprator_seprator_separator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seprator',
            name='separator',
            field=models.IntegerField(default=0),
        ),
    ]
