# Generated by Django 4.2.5 on 2023-10-08 07:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0016_alter_seprator_separator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seprator',
            new_name='Separator',
        ),
    ]
