# Generated by Django 3.2.21 on 2023-10-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0017_rename_seprator_separator'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='lang',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
