# Generated by Django 4.2.5 on 2023-09-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_category_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
