# Generated by Django 4.2.5 on 2023-09-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_category_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
