# Generated by Django 3.2.21 on 2023-10-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lang',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
