# Generated by Django 4.2.5 on 2023-09-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0005_alter_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
