# Generated by Django 4.2.5 on 2023-09-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0006_alter_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
