# Generated by Django 3.2.21 on 2023-10-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_alter_starsmodel_breastsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='lang',
            field=models.CharField(db_index=True, max_length=3),
        ),
    ]
