# Generated by Django 4.2.3 on 2023-09-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0002_remove_comment_username_comment_movie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
    ]
