# Generated by Django 3.2.21 on 2023-10-21 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='StarsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='stars/')),
                ('haircolor', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('dob', models.DateField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=200, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('tatoo', models.CharField(blank=True, max_length=600, null=True)),
                ('piercing', models.CharField(blank=True, max_length=200, null=True)),
                ('breasttype', models.CharField(blank=True, max_length=100, null=True)),
                ('breastsize', models.CharField(blank=True, max_length=10, null=True)),
                ('bodymarking', models.CharField(blank=True, max_length=30, null=True)),
                ('currentstatus', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('modeltype', models.CharField(blank=True, max_length=30, null=True)),
                ('eyecolor', models.CharField(blank=True, max_length=200, null=True)),
                ('bodytype', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('lang', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('quality', models.CharField(default=False, max_length=50)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('coverphoto', models.ImageField(null=True, upload_to='coverphoto/')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('short_description', models.TextField(max_length=100000)),
                ('trailer', models.FileField(blank=True, null=True, upload_to='trailer/')),
                ('price', models.FloatField()),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('cart_count', models.IntegerField(default=0)),
                ('lang', models.CharField(max_length=3)),
                ('videoname', models.TextField(blank=True)),
                ('genre', models.ManyToManyField(blank=True, to='category.Category')),
                ('images', models.ManyToManyField(blank=True, related_name='related_images', to='indexapp.ImagesModel')),
                ('stars', models.ManyToManyField(blank=True, related_name='stars', to='indexapp.StarsModel')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexapp.studiomodel')),
            ],
        ),
        migrations.CreateModel(
            name='FavouritesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_movies', models.ManyToManyField(to='indexapp.MovieDetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
