# Generated by Django 4.2.5 on 2023-09-16 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('duration', models.TimeField()),
                ('short_description', models.CharField(max_length=100000)),
                ('thumbnail', models.ImageField(upload_to='thumbanils')),
                ('trailer', models.FileField(upload_to='trailer')),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('movie_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.moviedetail')),
            ],
        ),
    ]
