# Generated by Django 4.2.5 on 2023-09-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='coverphoto',
            field=models.ImageField(null=True, upload_to='coverphoto'),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='short_description',
            field=models.TextField(max_length=100000),
        ),
    ]
