# Generated by Django 4.2.5 on 2023-09-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_moviedetail_coverphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='link',
            field=models.URLField(default=False),
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='quality',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
