# Generated by Django 4.2.5 on 2023-09-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0003_moviedetail_link_moviedetail_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='genere',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
    ]
