# Generated by Django 4.2.5 on 2023-09-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0004_moviedetail_genere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='coverphoto',
            field=models.ImageField(null=True, upload_to='coverphoto/'),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbanils/'),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='trailer',
            field=models.FileField(upload_to='trailer/'),
        ),
    ]
