# Generated by Django 3.2.21 on 2023-09-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0006_auto_20230917_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='slug',
            field=models.SlugField(),
        ),
    ]
