# Generated by Django 3.2.21 on 2023-09-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0007_alter_moviedetail_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='moviedetail',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='images',
            field=models.ManyToManyField(related_name='related_images', to='indexapp.ImagesModel'),
        ),
    ]
