# Generated by Django 4.2.5 on 2023-09-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0008_auto_20230917_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='created_at',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
