# Generated by Django 3.2.21 on 2023-09-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0011_alter_moviedetail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
