# Generated by Django 4.2.3 on 2023-09-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0014_alter_moviedetail_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='starsmodel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='starsmodel',
            name='haircolor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='starsmodel',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
