# Generated by Django 4.2.3 on 2023-09-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0015_starsmodel_age_starsmodel_haircolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='stars', to='indexapp.starsmodel'),
        ),
    ]
