# Generated by Django 4.2.3 on 2023-09-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0017_studiomodel_moviedetail_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='created_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='trailer/'),
        ),
    ]
