# Generated by Django 4.2.3 on 2023-09-24 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0018_alter_moviedetail_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexapp.studiomodel'),
        ),
    ]
