# Generated by Django 3.2.21 on 2023-10-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0021_alter_moviedetail_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='cart_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
