# Generated by Django 3.2.21 on 2023-10-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0022_auto_20231001_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='starsmodel',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
