# Generated by Django 4.2.3 on 2023-10-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0023_starsmodel_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starsmodel',
            name='age',
        ),
        migrations.AddField(
            model_name='starsmodel',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
