# Generated by Django 4.2.3 on 2023-10-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0024_remove_starsmodel_age_starsmodel_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='starsmodel',
            name='birthplace',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='starsmodel',
            name='bodytype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='starsmodel',
            name='breast',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='starsmodel',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='starsmodel',
            name='eyecolor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='starsmodel',
            name='nationality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='starsmodel',
            name='piercing',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='starsmodel',
            name='tatoo',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='starsmodel',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
