# Generated by Django 4.2.3 on 2023-10-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0025_starsmodel_birthplace_starsmodel_bodytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='related_images', to='indexapp.imagesmodel'),
        ),
    ]
