# Generated by Django 3.2.21 on 2023-10-03 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indexapp', '0025_starsmodel_birthplace_starsmodel_bodytype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_movies', models.ManyToManyField(to='indexapp.MovieDetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
