# Generated by Django 4.2.5 on 2023-10-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0026_alter_moviedetail_images'),
        ('indexapp', '0026_favouritesmodel'),
    ]

    operations = [
    ]
