# Generated by Django 3.2.21 on 2023-10-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0027_merge_20231004_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starsmodel',
            old_name='breast',
            new_name='breasttype',
        ),
        migrations.AddField(
            model_name='starsmodel',
            name='bodymarking',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='starsmodel',
            name='breastsize',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='starsmodel',
            name='currentstatus',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='starsmodel',
            name='gender',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='starsmodel',
            name='modeltype',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
