# Generated by Django 4.2.5 on 2023-10-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0028_auto_20231013_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='starsmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
