# Generated by Django 3.2.21 on 2023-10-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0029_starsmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='lang',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='starsmodel',
            name='lang',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='studiomodel',
            name='lang',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
