# Generated by Django 3.2.21 on 2023-10-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0030_auto_20231019_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='lang',
            field=models.CharField(max_length=3),
        ),
    ]
