# Generated by Django 3.2.21 on 2023-10-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
