# Generated by Django 4.2.5 on 2023-10-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_account_user_password'),
        ('myaccount', '0003_alter_account_is_active'),
    ]

    operations = [
    ]
