# Generated by Django 3.2.21 on 2023-10-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('status', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('lang', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
