# Generated by Django 4.2.6 on 2023-10-22 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_category_name_alter_category_slug'),
        ('category', '0002_auto_20231021_1607'),
    ]

    operations = [
    ]
