# Generated by Django 4.2.5 on 2023-09-22 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0012_moviedetail_type'),
        ('detailapp', '0004_remove_cartitem_product_album_alter_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indexapp.moviedetail'),
        ),
    ]
