# Generated by Django 4.2.5 on 2023-09-22 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0012_moviedetail_type'),
        ('detailapp', '0006_remove_cartitem_product_cartitem_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indexapp.moviedetail'),
        ),
    ]
