# Generated by Django 4.2.5 on 2023-09-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0007_remove_cartitem_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
