# Generated by Django 4.2.5 on 2023-09-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0008_order_product_limit_alter_order_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='limit',
        ),
        migrations.AddField(
            model_name='order_product',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
