# Generated by Django 4.2.5 on 2023-09-28 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_albums_genre'),
        ('detailapp', '0009_remove_order_product_limit_order_product_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.albums'),
        ),
    ]
