# Generated by Django 4.2.5 on 2023-09-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0011_remove_cartitem_product1_cartalbum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartalbum',
        ),
    ]
