# Generated by Django 4.2.5 on 2023-10-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0015_album_item'),
        ('detailapp', '0016_alter_order_payment'),
    ]

    operations = [
    ]
