# Generated by Django 4.2.5 on 2023-10-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_remove_albums_counter_albummovie_counter'),
        ('detailapp', '0019_order_product_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product_album',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.albummovie'),
        ),
    ]
