# Generated by Django 4.2.5 on 2023-10-07 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0020_alter_order_product_album_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line_2',
            new_name='zip_code',
        ),
    ]
