# Generated by Django 4.2.5 on 2023-10-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0021_rename_address_line_2_order_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
